export const SET_CREDENTIALS_EMAIL = 'SET_CREDENTIALS_EMAIL'
export const SET_CREDENTIALS_PASSWORD = 'SET_CREDENTIALS_PASSWORD'

export const SIGNUP_EMAIL_REQUEST = 'SIGNUP_EMAIL_REQUEST'
export const SIGNUP_EMAIL_SUCCESS = 'SIGNUP_EMAIL_SUCCESS'
export const SIGNUP_EMAIL_FAILURE = 'SIGNUP_EMAIL_FAILURE'

export const SIGNIN_GOOGLE_REQUEST = 'SIGNIN_GOOGLE_REQUEST'
export const SIGNIN_GOOGLE_SUCCESS = 'SIGNIN_GOOGLE_SUCCESS'
export const SIGNIN_GOOGLE_FAILURE = 'SIGNIN_GOOGLE_FAILURE'

export const SET_MESSAGE_TO_SEND = 'SET_MESSAGE_TO_SEND'

export const POST_TO_CHATROOM_REQUEST = 'POST_TO_CHATROOM_REQUEST'
export const POST_TO_CHATROOM_SUCCESS = 'POST_TO_CHATROOM_SUCCESS'
export const POST_TO_CHATROOM_FAILURE = 'POST_TO_CHATROOM_FAILURE'
