export const SET_CREDENTIALS_EMAIL = 'SET_CREDENTIALS_EMAIL'
export const SET_CREDENTIALS_PASSWORD = 'SET_CREDENTIALS_PASSWORD'

export const SIGNUP_EMAIL_REQUEST = 'SIGNUP_EMAIL_REQUEST'
export const SIGNUP_EMAIL_SUCCESS = 'SIGNUP_EMAIL_SUCCESS'
export const SIGNUP_EMAIL_FAILURE = 'SIGNUP_EMAIL_FAILURE'
